FROM docker.io/alpine:3.23.3@sha256:25109184c71bdad752c8312a8623239686a9a2071e8825f20acb8f2198c3f659 AS downloader

ARG VERSION="7.3.2"
ARG TARGETARCH

RUN apk add --no-cache curl

RUN BASE_URL="https://github.com/owncloud/ocis/releases/download/v${VERSION}" && \
  curl -fsSL "${BASE_URL}/ocis-${VERSION}-linux-${TARGETARCH}" -o /usr/bin/ocis && \
  curl -fsSL "${BASE_URL}/ocis-${VERSION}-linux-${TARGETARCH}.sha256" -o /tmp/ocis.sha256 && \
  EXPECTED=$(awk '{print $1}' /tmp/ocis.sha256) && \
  echo "${EXPECTED}  /usr/bin/ocis" | sha256sum -c - && \
  chmod +x /usr/bin/ocis

FROM docker.io/alpine:3.23.3@sha256:25109184c71bdad752c8312a8623239686a9a2071e8825f20acb8f2198c3f659

ARG VERSION=""
ARG REVISION=""

RUN apk add --no-cache attr bash ca-certificates curl inotify-tools libc6-compat mailcap tree vips patch && \
  echo 'hosts: files dns' >| /etc/nsswitch.conf

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>" \
  org.opencontainers.image.title="ownCloud Infinite Scale" \
  org.opencontainers.image.vendor="ownCloud GmbH" \
  org.opencontainers.image.authors="ownCloud GmbH" \
  org.opencontainers.image.description="oCIS - ownCloud Infinite Scale is a modern file-sync and share platform" \
  org.opencontainers.image.licenses="Apache-2.0" \
  org.opencontainers.image.documentation="https://github.com/owncloud/ocis" \
  org.opencontainers.image.url="https://hub.docker.com/r/owncloud/ocis" \
  org.opencontainers.image.source="https://github.com/owncloud/ocis" \
  org.opencontainers.image.version="${VERSION}" \
  org.opencontainers.image.revision="${REVISION}"

RUN addgroup -g 1000 -S ocis-group && \
  adduser -S --ingroup ocis-group --uid 1000 ocis-user --home /var/lib/ocis

RUN mkdir -p /var/lib/ocis && \
  chown -R ocis-user:ocis-group /var/lib/ocis && \
  chmod -R 751 /var/lib/ocis && \
  mkdir -p /etc/ocis && \
  chown -R ocis-user:ocis-group /etc/ocis && \
  chmod -R 751 /etc/ocis

VOLUME [ "/var/lib/ocis", "/etc/ocis" ]

WORKDIR /var/lib/ocis

USER 1000

EXPOSE 9200/tcp

ENTRYPOINT ["/usr/bin/ocis"]

CMD ["server"]

COPY --from=downloader /usr/bin/ocis /usr/bin/ocis
