FROM docker.io/alpine:3.23.4@sha256:5b10f432ef3da1b8d4c7eb6c487f2f5a8f096bc91145e68878dd4a5019afde11 AS node-builder

ARG VERSION="8.0.1"

RUN apk add --no-cache nodejs npm curl git make

RUN npm install -g pnpm@10.28.1

RUN git clone --depth 1 --branch "v${VERSION}" https://github.com/owncloud/ocis.git /build

WORKDIR /build/services/idp
RUN pnpm install --frozen-lockfile
RUN pnpm build
RUN curl -fsSL https://raw.githubusercontent.com/owncloud/assets/main/favicon.ico \
      -o assets/identifier/static/favicon.ico

WORKDIR /build/services/web
RUN make pull-assets


FROM docker.io/alpine:3.23.4@sha256:5b10f432ef3da1b8d4c7eb6c487f2f5a8f096bc91145e68878dd4a5019afde11 AS go-builder

ARG VERSION="8.0.1"
ARG TARGETARCH

RUN apk add --no-cache go gcc musl-dev libvips-dev curl-dev make git

COPY --from=node-builder /build /build

WORKDIR /build/ocis

RUN CGO_ENABLED=1 ENABLE_VIPS=true \
    make release-linux-docker-${TARGETARCH} VERSION=${VERSION}


FROM docker.io/alpine:3.23.4@sha256:5b10f432ef3da1b8d4c7eb6c487f2f5a8f096bc91145e68878dd4a5019afde11

ARG VERSION=""
ARG REVISION=""
ARG TARGETARCH

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>" \
  org.opencontainers.image.title="ownCloud Infinite Scale" \
  org.opencontainers.image.vendor="ownCloud GmbH" \
  org.opencontainers.image.authors="ownCloud GmbH" \
  org.opencontainers.image.description="oCIS - ownCloud Infinite Scale is a modern file-sync and share platform" \
  org.opencontainers.image.licenses="Apache-2.0" \
  org.opencontainers.image.documentation="https://github.com/owncloud/ocis" \
  org.opencontainers.image.url="https://hub.docker.com/r/owncloud/ocis" \
  org.opencontainers.image.source="https://github.com/owncloud/ocis" \
  org.opencontainers.image.version="${VERSION}" \
  org.opencontainers.image.revision="${REVISION}"

RUN apk add --no-cache attr bash ca-certificates curl inotify-tools libc6-compat mailcap tree vips patch && \
  echo 'hosts: files dns' >| /etc/nsswitch.conf

RUN addgroup -g 1000 -S ocis-group && \
  adduser -S --ingroup ocis-group --uid 1000 ocis-user --home /var/lib/ocis

RUN mkdir -p /var/lib/ocis && \
  chown -R ocis-user:ocis-group /var/lib/ocis && \
  chmod -R 751 /var/lib/ocis && \
  mkdir -p /etc/ocis && \
  chown -R ocis-user:ocis-group /etc/ocis && \
  chmod -R 751 /etc/ocis

COPY --from=go-builder /build/ocis/dist/binaries/ocis-linux-${TARGETARCH} /usr/bin/ocis

VOLUME [ "/var/lib/ocis", "/etc/ocis" ]

WORKDIR /var/lib/ocis

USER 1000

EXPOSE 9200/tcp

ENTRYPOINT ["/usr/bin/ocis"]

CMD ["server"]
